<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class LiftingPermit extends Model
{
    protected $fillable = [
        'lokasi_pekerjaan',
        'tanggal_pekerjaan',
        'uraian_pekerjaan',
        'peralatan_digunakan',
        'jumlah_pekerja',
        'nomor_darurat',
        'dokumentasi_persyaratan',
        'persyaratan_kerja_aman',
        'rekomendasi_kerja_aman',
        'rekomendasi_status',
        'permit_requestor_name',
        'signature_permit_requestor',
        'permit_requestor_date',
        'permit_requestor_time',
        'verificator_name',
        'signature_verificator',
        'verificator_date',
        'verificator_time',
        'permit_issuer_name',
        'signature_permit_issuer',
        'permit_issuer_date',
        'permit_issuer_time',
        'izin_berlaku_dari',
        'izin_berlaku_jam_dari',
        'izin_berlaku_sampai',
        'izin_berlaku_jam_sampai',
        'permit_authorizer_name',
        'signature_permit_authorizer',
        'permit_authorizer_date',
        'permit_authorizer_time',
        'permit_receiver_name',
        'signature_permit_receiver',
        'permit_receiver_date',
        'permit_receiver_time',
        'penutupan_izin_kerja',
        'close_date',
        'close_time',
        'signature_close_requestor',
        'signature_close_issuer',
    ];

    protected $casts = [
        'dok_operator' => 'array',
        'dok_rigger' => 'array',
        'dok_sertifikat' => 'array',
        'dok_loadchart' => 'array',
        'dok_rencana_pengangkatan' => 'array',
        'dok_jsa' => 'array',
        'persyaratan_kerja_aman' => 'array',
        'penutupan_izin_kerja' => 'array',
        'rekomendasi_status' => 'boolean',
        'tanggal_pekerjaan' => 'date',
        'permit_requestor_date' => 'date',
        'verificator_date' => 'date',
        'permit_issuer_date' => 'date',
        'izin_berlaku_dari' => 'date',
        'izin_berlaku_sampai' => 'date',
        'permit_authorizer_date' => 'date',
        'permit_receiver_date' => 'date',
        'close_date' => 'date',
        'permit_requestor_time' => 'datetime:H:i',
        'verificator_time' => 'datetime:H:i',
        'permit_issuer_time' => 'datetime:H:i',
        'izin_berlaku_jam_dari' => 'datetime:H:i',
        'izin_berlaku_jam_sampai' => 'datetime:H:i',
        'permit_authorizer_time' => 'datetime:H:i',
        'permit_receiver_time' => 'datetime:H:i',
        'close_time' => 'datetime:H:i',
    ];
}
